---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Build backend image.
      docker_image:
        build:
          path: ./backend
          dockerfile: backend.dockerfile
          pull: yes
        name: fastapi-ml-backend
        tag: latest
        push: no
        source: build
        debug: yes