---
- hosts: localhost
  gather_facts: false

  vars_files:
    - "vars/{{ environment }}/main.yml"

  tasks:
    - name: Deploy Python app.
      k8s:
        definition: '{{ item }}'
        kubeconfig: '{{ k8s_kubeconfig }}'
        state: present
      loop:
        - "{{ lookup('template', 'kubernetes-templates/fastapi-ml-deployment.yml') | from_yaml_all | list }}"
        - "{{ lookup('template', 'kubernetes-templates/fastapi-ml-service.yml') | from_yaml_all | list }}"